apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  namespace: cicd-app
spec:
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
